name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'Build/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'Build/**'
  workflow_dispatch:

jobs:
  build-logstash:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image for Logstash
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Build/Dockerfile-logstash
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          ${{ vars.DOCKER_USERNAME }}/atmos-logstash:latest
          ${{ vars.DOCKER_USERNAME }}/atmos-logstash:${{ github.sha }}

  build-dashboards:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image for Dashboards
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Build/Dockerfile-dashboard
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          ${{ vars.DOCKER_USERNAME }}/atmos-dashboards:latest
          ${{ vars.DOCKER_USERNAME }}/atmos-dashboards:${{ github.sha }}